### ISSUE TITLE
Logo design contribution

### ISSUE THREAD

**Issue by saifulfrank** [oxdc/brdnote#2]
Hi
I want to make a logo for this projects if you have any requirements then let me know.its totally free for open source projects.

**Comment by oxdc** [comment]
@saifulfrank Woh, that's great! Thanks a lot! There won't be any special requirement. I just ... randomly downloaded one from the Internet.

Besides, I have to remind you that this project is still under development and portions of it may still be ... pretty bad! I hope you can use it until I publish the first release (not alpha or beta release).

**BE CAREFUL!! IT MAY CAUSE DATA LOSES UNDER ALPHA VERSIONS.**
